const cfg=window.TCB_CONFIG||{};let supabaseClient=null;
if(cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&window.supabase) supabaseClient=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let content=structuredClone(window.TCB_CONTENT||{}), currentAdmin=false, articleData=[], carData=[], galleryData=[];
const defaults={hero:{title:"Cars.\nModifications.\nStories.",description:"Real cars. Real builds. Real stories — from an automotive creator building something bigger than a social feed."},about:{intro:"This is the home base for everything I do around cars — beyond Instagram, beyond a single reel, and eventually beyond social media.",text:"BMW, cars, modifications, restoration and the real stories behind the machines. This website grows with the journey."},settings:{instagram:"https://www.instagram.com/asif_king_ahmed/",youtube:"https://www.youtube.com/@asifkingahmed",email:"asifahmedmedia@gmail.com",siteTitle:"Asif King Ahmed | Cars • Modifications • Stories",metaDescription:"Asif King Ahmed — automotive creator. Cars, modifications, builds, stories and TCB Auto.",announcement:""},layout:{order:["home","articles","about","cars","gallery","tcb","stories","contact"],hidden:[]}};
content={...defaults,...content};
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function slugify(v){return String(v||"").toLowerCase().trim().replace(/[^a-z0-9\s-]/g,"").replace(/\s+/g,"-").replace(/-+/g,"-").slice(0,90)}
function textToLines(v){return esc(v).replace(/\n/g,"<br>")}
function setLinks(){const s=content.settings||defaults.settings;["heroInstagram","aboutInstagram"].forEach(id=>{const e=$("#"+id);if(e)e.href=s.instagram||"#"});const y=$("#heroYoutube");if(y)y.href=s.youtube||"#";const m=$("#contactMail");if(m){m.href="mailto:"+(s.email||"");m.querySelector("strong").textContent=s.email||""}document.title=s.siteTitle||defaults.settings.siteTitle;document.querySelector('meta[name="description"]').setAttribute("content",s.metaDescription||defaults.settings.metaDescription)}
function renderHero(){const h=content.hero||defaults.hero;$("#heroTitle").innerHTML=textToLines(h.title).replace(/Modifications\./g,"<span>Modifications.</span>");$("#heroDesc").textContent=h.description||"";const a=content.about||defaults.about;$("#aboutIntro").textContent=a.intro||"";$("#aboutText").textContent=a.text||"";setLinks()}
async function loadSiteContent(){if(!supabaseClient)return;const {data,error}=await supabaseClient.from("site_content").select("content_key,value");if(error){console.warn(error.message);return}for(const row of data||[])content[row.content_key]=row.value;renderHero();applyLayout();}
function navItems(){const labels={home:"Home",articles:"Articles",about:"About",cars:"My Cars",gallery:"Gallery",tcb:"TCB Auto",stories:"Stories",contact:"Contact"};const order=content.layout?.order||defaults.layout.order;const hidden=content.layout?.hidden||[];return order.filter(x=>labels[x]&&!hidden.includes(x)).map(x=>`<a href="#${x}">${labels[x]}</a>`).join("")}
function initMenu(){$("#nav").innerHTML=navItems();const close=()=>{$("#nav").classList.remove("open");$("#menuBtn").setAttribute("aria-expanded","false")};$("#menuBtn")?.addEventListener("click",()=>{$("#nav").classList.toggle("open");$("#menuBtn").setAttribute("aria-expanded",$("#nav").classList.contains("open"))});$("#nav").addEventListener("click",e=>{if(e.target.matches("a"))close()});window.addEventListener("hashchange",()=>{const id=location.hash.slice(1);if(id&&$("#"+id)) $$("#nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+id))});}
function applyLayout(){const order=content.layout?.order||defaults.layout.order;const hidden=content.layout?.hidden||[];const main=$("#publicSite");const secs=order.map(id=>$("#"+id)).filter(Boolean);secs.forEach(s=>main.appendChild(s));$$(".page-section").forEach(s=>s.classList.toggle("section-hidden",hidden.includes(s.id)));if($("#admin"))main.appendChild($("#admin"));initMenu();renderSectionOrder()}
function renderSectionOrder(){const box=$("#sectionOrder");if(!box)return;const labels={home:"Home",articles:"Articles",about:"About",cars:"My Cars",gallery:"Gallery",tcb:"TCB Auto",stories:"Stories",contact:"Contact"};const order=content.layout?.order||defaults.layout.order,hidden=content.layout?.hidden||[];box.innerHTML=order.map(id=>`<div class="sortable-item" draggable="true" data-id="${id}"><span class="drag">☷</span><b>${labels[id]}</b><label class="switch"><input type="checkbox" data-section="${id}" ${hidden.includes(id)?"":"checked"}><span></span></label></div>`).join("");let dragged=null;$$('#sectionOrder .sortable-item').forEach(el=>{el.addEventListener('dragstart',()=>{dragged=el;el.classList.add('dragging')});el.addEventListener('dragend',()=>{el.classList.remove('dragging');dragged=null});el.addEventListener('dragover',e=>{e.preventDefault();if(dragged&&dragged!==el){const r=el.getBoundingClientRect();const after=e.clientY-r.top>r.height/2;el.parentNode.insertBefore(dragged,after?el.nextSibling:el)}})});}
function tabs(){$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));$$(".tab-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active")})}
async function isAdmin(session){if(!session)return false;const {data,error}=await supabaseClient.from("admin_users").select("user_id").eq("user_id",session.user.id).maybeSingle();if(error){console.error(error);return false}return !!data}
function flash(msg,error=false){const state=$("#adminState");if(!state)return;const n=document.createElement("div");n.className="admin-msg"+(error?" admin-error":"");n.textContent=msg;state.appendChild(n);setTimeout(()=>n.remove(),4500)}
async function upsertContent(key,value){const {error}=await supabaseClient.from("site_content").upsert({content_key:key,value,updated_at:new Date().toISOString()},{onConflict:"content_key"});if(error){flash(error.message,true);return false}content[key]=value;renderHero();applyLayout();flash("Saved successfully.");return true}
function sanitizeHTML(html){const allowed=new Set(["B","STRONG","I","EM","H2","H3","P","BR","UL","OL","LI","BLOCKQUOTE","A"]);const doc=new DOMParser().parseFromString(html||"","text/html");doc.body.querySelectorAll("*").forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return}for(const a of [...el.attributes]){if(el.tagName==="A"&&a.name==="href"&&/^https?:\/\//i.test(a.value))continue;el.removeAttribute(a.name)}if(el.tagName==="A"){el.setAttribute("target","_blank");el.setAttribute("rel","noopener")}});return doc.body.innerHTML}
function articleImage(a){return a.cover_url||a.image_url||""}
function renderArticles(data){const grid=$("#articleGrid");const pub=(data||[]).filter(a=>a.published).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));if(!pub.length){grid.innerHTML=`<article class="empty-public"><span>ARTICLES</span><h3>Nothing published yet.</h3><p>Your next article will appear here automatically when you publish it from Admin.</p><a href="#admin">Open Admin ↗</a></article>`;return}grid.innerHTML=pub.slice(0,9).map((a,i)=>{const img=articleImage(a);return `<article class="article-card ${i===0?"featured-article":""}"><button class="article-click" data-article="${a.id}"><div class="article-art" ${img?`style="background-image:linear-gradient(transparent 30%,rgba(0,0,0,.78)),url('${esc(img)}')"`:""}><span>ARTICLE</span><b>${String(i+1).padStart(2,"0")}</b></div><div class="article-body"><small>${new Date(a.created_at).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"})}</small><h3>${esc(a.title)}</h3><p>${esc(a.excerpt||"")}</p><span class="read-link">Read Article ↗</span></div></button></article>`}).join("");$$('[data-article]').forEach(b=>b.addEventListener('click',()=>openReader(Number(b.dataset.article))));}
async function refreshArticles(){const {data,error}=await supabaseClient.from("articles").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:false});if(error){flash(error.message,true);return}articleData=data||[];$("#articleAdminList").innerHTML=articleData.map(a=>`<div class="admin-item"><div class="admin-item-main">${articleImage(a)?`<img src="${esc(articleImage(a))}" alt="">`:""}<div><b>${esc(a.title)}</b><span>${a.published?"Published":"Draft"} • ${a.slug||""}</span></div></div><div class="admin-item-actions"><button onclick='window.editArticle(${JSON.stringify(a).replace(/'/g,"&#39;")})'>Edit</button><button onclick='window.deleteArticle(${a.id})'>Delete</button></div></div>`).join("")||'<div class="admin-msg">No articles yet.</div>';renderArticles(articleData)}
function resetUpload(id,previewId){const i=$("#"+id);if(i)i.value="";const p=$("#"+previewId);if(p){p.hidden=true;p.src=""}}
async function uploadFiles(files,folder){if(!files?.length)return [];if(!supabaseClient)return [];const out=[];for(const file of files){if(!file.type.startsWith("image/"))continue;if(file.size>12*1024*1024){flash(`${file.name} is over 12MB.`,true);continue}const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabaseClient.storage.from("site-media").upload(path,file,{cacheControl:"31536000",upsert:false,contentType:file.type});if(error){flash(`Upload failed: ${error.message}`,true);continue}const {data}=supabaseClient.storage.from("site-media").getPublicUrl(path);out.push(data.publicUrl)}return out}
function setupDropzones(){const zones=$$(".dropzone");zones.forEach(zone=>{const input=zone.querySelector('input[type=file]');zone.addEventListener("click",e=>{if(e.target!==input)input.click()});["dragenter","dragover"].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.add("dragover")}));["dragleave","drop"].forEach(ev=>zone.addEventListener(ev,e=>{e.preventDefault();zone.classList.remove("dragover")}));zone.addEventListener("drop",e=>{input.files=e.dataTransfer.files;input.dispatchEvent(new Event("change",{bubbles:true}))});});$("#articleCoverInput").onchange=e=>previewSingle(e.target.files[0],"#articleCoverPreview");$("#carCoverInput").onchange=e=>previewSingle(e.target.files[0],"#carCoverPreview");$("#carGalleryInput").onchange=e=>previewThumbs(e.target.files,"#carGalleryPreview");$("#galleryInput").onchange=e=>previewThumbs(e.target.files,"#galleryPreview")}
function previewSingle(file,sel){const p=$(sel);if(!file){p.hidden=true;return}p.src=URL.createObjectURL(file);p.hidden=false}
function previewThumbs(files,sel){const box=$(sel);box.innerHTML="";[...files].forEach(f=>{if(f.type.startsWith("image/")){const img=document.createElement("img");img.src=URL.createObjectURL(f);box.appendChild(img)}})}
function openReader(id){const a=articleData.find(x=>Number(x.id)===Number(id));if(!a)return;$("#readerTitle").textContent=a.title;$("#readerExcerpt").textContent=a.excerpt||"";$("#readerMeta").textContent=`${new Date(a.created_at).toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"})} • ASIF KING AHMED`;$("#readerBody").innerHTML=sanitizeHTML(a.body||"<p>No article body yet.</p>");const img=articleImage(a);const cover=$("#readerCover");cover.style.backgroundImage=img?`linear-gradient(transparent,rgba(0,0,0,.35)),url('${esc(img)}')`:"";cover.classList.toggle("has-image",!!img);$("#articleModal").hidden=false;document.body.classList.add("modal-open");history.replaceState(null,"",`#article/${a.slug||a.id}`)}
function closeReader(){$("#articleModal").hidden=true;document.body.classList.remove("modal-open");if(location.hash.startsWith("#article/"))history.replaceState(null,"",location.pathname+location.search)}
async function initAdmin(){const state=$("#adminState"),panel=$("#adminPanel");if(!state||!panel)return;if(!supabaseClient){state.innerHTML='<div class="admin-msg admin-error">Supabase is not connected. Check config.js.</div>';return}const {data:{session}}=await supabaseClient.auth.getSession();await show(session);supabaseClient.auth.onAuthStateChange((_e,s)=>setTimeout(()=>show(s),0));
 async function show(session){if(!(await isAdmin(session))){currentAdmin=false;panel.hidden=true;state.innerHTML=`<form id="loginForm" class="login-box"><div><span class="eyebrow">PRIVATE ACCESS</span><h3>Sign in to your control room.</h3></div><label>Email<input id="loginEmail" type="email" required autocomplete="email" placeholder="Admin email"></label><label>Password<input id="loginPassword" type="password" required autocomplete="current-password" placeholder="Password"></label><button class="btn primary" type="submit">Sign in</button><div id="loginMsg"></div></form>`;$("#loginForm").onsubmit=async e=>{e.preventDefault();const msg=$("#loginMsg");msg.className="admin-msg";msg.textContent="Signing in…";const {error}=await supabaseClient.auth.signInWithPassword({email:$("#loginEmail").value.trim(),password:$("#loginPassword").value});if(error){msg.className="admin-msg admin-error";msg.textContent=error.message}};return}
 currentAdmin=true;state.innerHTML="";panel.hidden=false;$("#adminUser").textContent=session.user.email||"";tabs();bindAdmin();loadAdminForms();await Promise.all([refreshArticles(),refreshCars(),refreshGallery()]);renderSectionOrder();
 }
 function bindAdmin(){if($("#logout").dataset.bound)return;$("#logout").dataset.bound="1";$("#logout").onclick=()=>supabaseClient.auth.signOut();$("#saveHero").onclick=async()=>{const ok=await upsertContent("hero",{title:$("#editHeroTitle").value,description:$("#editHeroDesc").value});if(ok)await upsertContent("about",{intro:$("#editAboutIntro").value,text:$("#editAboutText").value})};$("#newArticle").onclick=()=>openArticle();$("#cancelArticle").onclick=()=>$("#articleEditor").hidden=true;$("#saveArticle").onclick=saveArticle;$("#newCar").onclick=()=>openCar();$("#cancelCar").onclick=()=>$("#carEditor").hidden=true;$("#saveCar").onclick=saveCar;$("#newGallery").onclick=()=>openGallery();$("#cancelGallery").onclick=()=>$("#galleryEditor").hidden=true;$("#saveGallery").onclick=saveGallery;$("#saveSettings").onclick=()=>upsertContent("settings",{instagram:$("#setInstagram").value.trim(),youtube:$("#setYoutube").value.trim(),email:$("#setEmail").value.trim(),siteTitle:$("#setSiteTitle").value.trim(),metaDescription:$("#setMetaDescription").value.trim(),announcement:$("#setAnnouncement").value.trim()});$("#saveSectionOrder").onclick=saveLayout;$("#refreshAll").onclick=async()=>{await loadSiteContent();await refreshArticles();await refreshCars();await refreshGallery();flash("Site data refreshed.")};$$('.editor-tools button').forEach(b=>b.addEventListener('click',()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);$("#articleBody").focus()}));setupDropzones();}
 function loadAdminForms(){const h=content.hero||defaults.hero,a=content.about||defaults.about,s=content.settings||defaults.settings;$("#editHeroTitle").value=h.title||"";$("#editHeroDesc").value=h.description||"";$("#editAboutIntro").value=a.intro||"";$("#editAboutText").value=a.text||"";$("#setInstagram").value=s.instagram||"";$("#setYoutube").value=s.youtube||"";$("#setEmail").value=s.email||"";$("#setSiteTitle").value=s.siteTitle||"";$("#setMetaDescription").value=s.metaDescription||"";$("#setAnnouncement").value=s.announcement||"";$("#healthText").textContent=`${articleData.length} articles • ${carData.length} cars • ${galleryData.length} gallery items`}
 async function saveLayout(){const order=$$("#sectionOrder .sortable-item").map(x=>x.dataset.id);const hidden=$$("#sectionOrder input[type=checkbox]").filter(x=>!x.checked).map(x=>x.dataset.section);await upsertContent("layout",{order,hidden})}
 window.editArticle=a=>{$("#articleEditor").hidden=false;$("#articleId").value=a.id;$("#articleTitle").value=a.title||"";$("#articleSlug").value=a.slug||slugify(a.title);$("#articleExcerpt").value=a.excerpt||"";$("#articleBody").innerHTML=a.body||"";$("#articlePublished").checked=!!a.published;$("#articleSeoTitle").value=a.seo_title||"";$("#articleSeoDescription").value=a.seo_description||"";const img=articleImage(a);if(img){$("#articleCoverPreview").src=img;$("#articleCoverPreview").hidden=false}else resetUpload("articleCoverInput","articleCoverPreview");$("#articlesTab").scrollIntoView({behavior:"smooth",block:"start"})};
 window.deleteArticle=async id=>{if(!confirm("Delete this article?"))return;const {error}=await supabaseClient.from("articles").delete().eq("id",id);if(error)flash(error.message,true);else{flash("Article deleted.");await refreshArticles()}};
 function openArticle(){$("#articleEditor").hidden=false;$("#articleId").value="";$("#articleTitle").value="";$("#articleSlug").value="";$("#articleExcerpt").value="";$("#articleBody").innerHTML="";$("#articlePublished").checked=false;$("#articleSeoTitle").value="";$("#articleSeoDescription").value="";resetUpload("articleCoverInput","articleCoverPreview")}
 async function saveArticle(){const title=$("#articleTitle").value.trim();if(!title)return flash("Add an article title.",true);let slug=$("#articleSlug").value.trim()||slugify(title);const id=$("#articleId").value;const existing=articleData.find(a=>String(a.id)===String(id));if(!id){const clash=articleData.find(a=>a.slug===slug);if(clash)slug=`${slug}-${Date.now().toString().slice(-5)}`}let cover=existing?articleImage(existing):"";const files=$("#articleCoverInput").files;if(files?.length)cover=(await uploadFiles(files,"articles"))[0]||cover;const payload={title,slug,excerpt:$("#articleExcerpt").value.trim(),body:sanitizeHTML($("#articleBody").innerHTML),image_url:cover,cover_url:cover,published:$("#articlePublished").checked,seo_title:$("#articleSeoTitle").value.trim(),seo_description:$("#articleSeoDescription").value.trim(),updated_at:new Date().toISOString()};const q=id?supabaseClient.from("articles").update(payload).eq("id",id):supabaseClient.from("articles").insert(payload);const {error}=await q;if(error)flash(error.message,true);else{$("#articleEditor").hidden=true;flash(payload.published?"Article published successfully.":"Draft saved.");await refreshArticles()}}
 async function refreshCars(){const {data,error}=await supabaseClient.from("cars").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:false});if(error){flash(error.message,true);return}carData=data||[];$("#carAdminList").innerHTML=carData.map(c=>`<div class="admin-item"><div class="admin-item-main">${c.image_url?`<img src="${esc(c.image_url)}" alt="">`:""}<div><b>${esc(c.name)}</b><span>${esc(c.meta||"")} • ${c.published?"Visible":"Hidden"}</span></div></div><div class="admin-item-actions"><button onclick='window.editCar(${JSON.stringify(c).replace(/'/g,"&#39;")})'>Edit</button><button onclick='window.deleteCar(${c.id})'>Delete</button></div></div>`).join("")||'<div class="admin-msg">No cars yet.</div>';const pub=carData.filter(x=>x.published);$("#carGrid").innerHTML=pub.length?pub.slice(0,6).map(c=>`<article class="car-card big" ${c.image_url?`style="background-image:linear-gradient(transparent 20%,rgba(0,0,0,.82)),url('${esc(c.image_url)}')"`:""}><span>MY GARAGE</span><h3>${esc(c.name)}</h3><p>${esc(c.desc||"")}</p><em>${esc(c.meta||"")}</em></article>`).join(""):`<article class="empty-public"><span>MY GARAGE</span><h3>Your cars will live here.</h3><p>Add a car from Admin and publish it when you're ready.</p></article>`}
 window.editCar=c=>{$("#carEditor").hidden=false;$("#carId").value=c.id;$("#carName").value=c.name||"";$("#carMeta").value=c.meta||"";$("#carDesc").value=c.desc||"";$("#carPublished").checked=!!c.published;$("#carGalleryPreview").innerHTML=(c.gallery_urls||[]).map(u=>`<img src="${esc(u)}" alt="">`).join("");if(c.image_url){$("#carCoverPreview").src=c.image_url;$("#carCoverPreview").hidden=false}else resetUpload("carCoverInput","carCoverPreview")};window.deleteCar=async id=>{if(!confirm("Delete this car?"))return;const {error}=await supabaseClient.from("cars").delete().eq("id",id);if(error)flash(error.message,true);else{flash("Car deleted.");await refreshCars()}};
 function openCar(){$("#carEditor").hidden=false;$("#carId").value="";$("#carName").value="";$("#carMeta").value="";$("#carDesc").value="";$("#carPublished").checked=false;$("#carGalleryPreview").innerHTML="";resetUpload("carCoverInput","carCoverPreview");$("#carGalleryInput").value=""}
 async function saveCar(){const name=$("#carName").value.trim();if(!name)return flash("Add a car name.",true);const id=$("#carId").value,existing=carData.find(c=>String(c.id)===String(id));let cover=existing?.image_url||"",gallery=existing?.gallery_urls||[];if($("#carCoverInput").files?.length)cover=(await uploadFiles($("#carCoverInput").files,"cars"))[0]||cover;if($("#carGalleryInput").files?.length)gallery=[...gallery,...await uploadFiles($("#carGalleryInput").files,"cars")];const payload={name,meta:$("#carMeta").value.trim(),desc:$("#carDesc").value.trim(),image_url:cover,gallery_urls:gallery,published:$("#carPublished").checked,updated_at:new Date().toISOString()};const q=id?supabaseClient.from("cars").update(payload).eq("id",id):supabaseClient.from("cars").insert(payload);const {error}=await q;if(error)flash(error.message,true);else{$("#carEditor").hidden=true;flash("Car saved.");await refreshCars()}}
 async function refreshGallery(){const {data,error}=await supabaseClient.from("gallery").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:false});if(error){flash(error.message,true);return}galleryData=data||[];$("#galleryAdminList").innerHTML=galleryData.map(g=>`<div class="admin-item"><div class="admin-item-main">${g.image_url?`<img src="${esc(g.image_url)}" alt="">`:""}<div><b>${esc(g.caption||"Gallery image")}</b><span>${g.published?"Visible":"Hidden"}</span></div></div><div class="admin-item-actions"><button onclick='window.editGallery(${JSON.stringify(g).replace(/'/g,"&#39;")})'>Edit</button><button onclick='window.deleteGallery(${g.id})'>Delete</button></div></div>`).join("")||'<div class="admin-msg">No gallery photos yet.</div>';const pub=galleryData.filter(x=>x.published);$("#galleryGrid").innerHTML=pub.length?pub.slice(0,12).map(g=>`<button class="gallery-photo" data-gallery="${g.id}" style="background-image:linear-gradient(transparent 40%,rgba(0,0,0,.7)),url('${esc(g.image_url)}')"><span>${esc(g.caption||"")}</span></button>`).join(""):`<div class="gallery-placeholder wide">YOUR GARAGE<br><small>Photos you upload in Admin will appear here.</small></div>`}
 window.editGallery=g=>{$("#galleryEditor").hidden=false;$("#galleryId").value=g.id;$("#galleryCaption").value=g.caption||"";$("#galleryPublished").checked=!!g.published;$("#galleryPreview").innerHTML=g.image_url?`<img src="${esc(g.image_url)}" alt="">`:""};window.deleteGallery=async id=>{if(!confirm("Delete this gallery photo?"))return;const {error}=await supabaseClient.from("gallery").delete().eq("id",id);if(error)flash(error.message,true);else{flash("Gallery photo deleted.");await refreshGallery()}};
 function openGallery(){$("#galleryEditor").hidden=false;$("#galleryId").value="";$("#galleryCaption").value="";$("#galleryPublished").checked=true;$("#galleryPreview").innerHTML="";$("#galleryInput").value=""}
 async function saveGallery(){const id=$("#galleryId").value;const existing=galleryData.find(g=>String(g.id)===String(id));let urls=[];if($("#galleryInput").files?.length)urls=await uploadFiles($("#galleryInput").files,"gallery");if(!id){if(!urls.length)return flash("Drop at least one photo.",true);for(const u of urls){const {error}=await supabaseClient.from("gallery").insert({image_url:u,caption:$("#galleryCaption").value.trim(),published:$("#galleryPublished").checked});if(error){flash(error.message,true);return}}}else{const payload={caption:$("#galleryCaption").value.trim(),published:$("#galleryPublished").checked,updated_at:new Date().toISOString()};if(urls[0])payload.image_url=urls[0];const {error}=await supabaseClient.from("gallery").update(payload).eq("id",id);if(error)return flash(error.message,true)}$("#galleryEditor").hidden=true;flash("Gallery updated.");await refreshGallery()}
}
function bindPublicModal(){$$('[data-close-modal]').forEach(e=>e.addEventListener('click',closeReader))}
$("#year").textContent=new Date().getFullYear();renderHero();applyLayout();bindPublicModal();initAdmin();window.addEventListener("load",()=>{const m=location.hash.match(/^#article\/(.+)$/);if(m){const found=articleData.find(a=>(a.slug||String(a.id))===decodeURIComponent(m[1]));if(found)openReader(found.id)}});
