-- ASIF KING AHMED / TCB AUTO — FINAL CMS SCHEMA
-- Run this once in Supabase SQL Editor. It is safe to run on the existing V3 database.
-- It upgrades the existing tables instead of deleting your data.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role='admin')
);
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  content_key text unique not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text,
  excerpt text default '',
  body text default '',
  image_url text default '',
  cover_url text default '',
  published boolean not null default false,
  sort_order integer not null default 0,
  seo_title text default '',
  seo_description text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  name text not null,
  meta text default '',
  "desc" text default '',
  image_url text default '',
  gallery_urls text[] not null default '{}',
  published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text default '',
  published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.articles add column if not exists slug text;
alter table public.articles add column if not exists cover_url text default '';
alter table public.articles add column if not exists sort_order integer not null default 0;
alter table public.articles add column if not exists seo_title text default '';
alter table public.articles add column if not exists seo_description text default '';
alter table public.cars add column if not exists gallery_urls text[] not null default '{}';
alter table public.cars add column if not exists sort_order integer not null default 0;
alter table public.gallery add column if not exists sort_order integer not null default 0;

update public.articles set slug=lower(regexp_replace(regexp_replace(title,'[^a-zA-Z0-9\\s-]','','g'),'\\s+','-','g')) where coalesce(slug,'')='';
update public.articles set cover_url=image_url where coalesce(cover_url,'')='';

create unique index if not exists articles_slug_unique on public.articles(slug) where slug is not null and slug<>'';

alter table public.admin_users enable row level security;
alter table public.site_content enable row level security;
alter table public.articles enable row level security;
alter table public.cars enable row level security;
alter table public.gallery enable row level security;

-- Admin identity lookup: lets the signed-in account prove it is an admin.
drop policy if exists "admins can read own admin row" on public.admin_users;
create policy "admins can read own admin row" on public.admin_users for select to authenticated using (auth.uid()=user_id);

-- Public content reads.
drop policy if exists "public can read site content" on public.site_content;
create policy "public can read site content" on public.site_content for select using (true);
drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles" on public.articles for select using (published=true or exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "public can read published cars" on public.cars;
create policy "public can read published cars" on public.cars for select using (published=true or exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "public can read published gallery" on public.gallery;
create policy "public can read published gallery" on public.gallery for select using (published=true or exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

-- Admin writes.
do $$ declare t text; begin
  foreach t in array array['site_content','articles','cars','gallery'] loop
    execute format('drop policy if exists "admins insert %s" on public.%I',t,t);
    execute format('drop policy if exists "admins update %s" on public.%I',t,t);
    execute format('drop policy if exists "admins delete %s" on public.%I',t,t);
    execute format('create policy "admins insert %s" on public.%I for insert to authenticated with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()))',t,t);
    execute format('create policy "admins update %s" on public.%I for update to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()))',t,t);
    execute format('create policy "admins delete %s" on public.%I for delete to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()))',t,t);
  end loop;
end $$;

-- Initial content. Existing values are preserved.
insert into public.site_content(content_key,value) values
('hero','{"title":"Cars.\\nModifications.\\nStories.","description":"Real cars. Real builds. Real stories — from an automotive creator building something bigger than a social feed."}'::jsonb),
('about','{"intro":"This is the home base for everything I do around cars — beyond Instagram, beyond a single reel, and eventually beyond social media.","text":"BMW, cars, modifications, restoration and the real stories behind the machines. This website grows with the journey."}'::jsonb),
('settings','{"instagram":"https://www.instagram.com/asif_king_ahmed/","youtube":"https://www.youtube.com/@asifkingahmed","email":"asifahmedmedia@gmail.com","siteTitle":"Asif King Ahmed | Cars • Modifications • Stories","metaDescription":"Asif King Ahmed — automotive creator. Cars, modifications, builds, stories and TCB Auto.","announcement":""}'::jsonb),
('layout','{"order":["home","articles","about","cars","gallery","tcb","stories","contact"],"hidden":[]}'::jsonb)
on conflict(content_key) do nothing;

-- Supabase Storage bucket for all website images.
insert into storage.buckets(id,name,public) values('site-media','site-media',true) on conflict(id) do update set public=true;

-- Storage policies: public can view; only your authenticated admin can upload/update/delete.
drop policy if exists "public can view site media" on storage.objects;
create policy "public can view site media" on storage.objects for select using (bucket_id='site-media');
drop policy if exists "admins can upload site media" on storage.objects;
create policy "admins can upload site media" on storage.objects for insert to authenticated with check (bucket_id='site-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can update site media" on storage.objects;
create policy "admins can update site media" on storage.objects for update to authenticated using (bucket_id='site-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (bucket_id='site-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins can delete site media" on storage.objects;
create policy "admins can delete site media" on storage.objects for delete to authenticated using (bucket_id='site-media' and exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
