-- ASIF KING AHMED / TCB AUTO V3 CMS
-- Run once in Supabase SQL Editor.
-- IMPORTANT: after creating your Auth user, replace ADMIN_USER_UUID below with that user's UUID.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role='admin')
);
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  content_key text unique not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text default '',
  body text default '',
  image_url text default '',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  name text not null,
  meta text default '',
  desc text default '',
  image_url text default '',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text default '',
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.site_content enable row level security;
alter table public.articles enable row level security;
alter table public.cars enable row level security;
alter table public.gallery enable row level security;

drop policy if exists "public can read site content" on public.site_content;
create policy "public can read site content" on public.site_content for select using (true);
drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles" on public.articles for select using (published=true or exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "public can read published cars" on public.cars;
create policy "public can read published cars" on public.cars for select using (published=true or exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "public can read published gallery" on public.gallery;
create policy "public can read published gallery" on public.gallery for select using (published=true or exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

-- Admin write policies.
do $$ declare t text; begin
  foreach t in array array['site_content','articles','cars','gallery'] loop
    execute format('drop policy if exists "admins insert %s" on public.%I',t,t);
    execute format('drop policy if exists "admins update %s" on public.%I',t,t);
    execute format('drop policy if exists "admins delete %s" on public.%I',t,t);
    execute format('create policy "admins insert %s" on public.%I for insert to authenticated with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()))',t,t);
    execute format('create policy "admins update %s" on public.%I for update to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()))',t,t);
    execute format('create policy "admins delete %s" on public.%I for delete to authenticated using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()))',t,t);
  end loop;
end $$;

insert into public.site_content(content_key,value) values
('hero','{"title":"Cars.\nModifications.\nStories.","description":"Real cars. Real builds. Real stories — from an automotive creator building something bigger than a social feed."}'::jsonb),
('settings','{"instagram":"https://www.instagram.com/asif_king_ahmed/","youtube":"https://www.youtube.com/@asifkingahmed","email":"asifahmedmedia@gmail.com"}'::jsonb)
on conflict(content_key) do nothing;

-- Add YOUR Supabase Auth user's UUID here:
-- insert into public.admin_users(user_id) values('ADMIN_USER_UUID');
