-- TCB Auto CMS
-- Run this in Supabase SQL Editor AFTER creating your Supabase Auth user.
-- Replace ADMIN_USER_UUID with your Auth user's UUID.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin'))
);

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  content_key text unique not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.site_content enable row level security;

-- Public visitors can read site content.
create policy "public can read site content"
on public.site_content for select
using (true);

-- Only registered admin users can insert/update/delete content.
create policy "admins can insert site content"
on public.site_content for insert
to authenticated
with check (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

create policy "admins can update site content"
on public.site_content for update
to authenticated
using (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
)
with check (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

create policy "admins can delete site content"
on public.site_content for delete
to authenticated
using (
  exists (select 1 from public.admin_users a where a.user_id = auth.uid())
);

-- Add your own Auth user UUID here:
-- insert into public.admin_users (user_id) values ('ADMIN_USER_UUID');

insert into public.site_content (content_key, value)
values
('hero', '{"eyebrow":"THE CAR BRO • TCB AUTO","title":"Cars. Culture. Stories.","description":"A premium automotive community built around real cars, real people and the stories behind them.","cta":"Explore TCB Auto"}'::jsonb),
('coming_soon', '{"used_cars":"Verified Used Cars are coming soon.","community":"TCB Stories and member profiles are coming soon.","marketplace":"Buy, sell & exchange listings are coming soon.","articles":"Editorial updates and Instagram-inspired articles are coming soon."}'::jsonb)
on conflict (content_key) do nothing;